project:
  type: website

website:
  title: "p-j-smith.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/p-j-smith
      - icon: linkedin
        href: https://www.linkedin.com/in/p-j-smith/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
