project:
  type: website

website:
  navbar:
    collapse: false
    left: 
      - icon: house-fill
        href: https://p-j-smith.github.io/
    right:
      - icon: person-circle
        href: https://p-j-smith.github.io/about.html
      - icon: github
        href: https://github.com/p-j-smith
      - icon: linkedin
        href: https://www.linkedin.com/in/p-j-smith/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
